name: Build

env:
  GO_VERSION: '1.25.4'

on:
  push:
    tags:
      - 'v*'
    branches:
      - '*'
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ env.GO_VERSION }}'
      - name: Run tests
        env:
          CI: "1"
        run: |-
          make test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if: "success() && matrix.os == 'ubuntu-latest'"
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  build:
    needs:
      - tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            platform: linux-x86_64
          - goos: linux
            goarch: arm64
            platform: linux-aarch64
          - goos: darwin
            goarch: amd64
            platform: darwin-x86_64
          - goos: darwin
            goarch: arm64
            platform: darwin-aarch64
          - goos: windows
            goarch: amd64
            platform: windows-x86_64
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ env.GO_VERSION }}'
      - name: Build release
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |-
          set -e -u -x

          RELEASE_VERSION="${GITHUB_REF##*/}"
          if [[ "${RELEASE_VERSION}" != v* ]]; then RELEASE_VERSION='dev'; fi
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV

          make VERBOSE=1 VERSION="${RELEASE_VERSION}" release

          ls -l build/dnsproxy-*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dnsproxy-${{ matrix.platform }}
          path: build/dnsproxy-*
      - name: Upload to release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/dnsproxy-*.tar.gz
            build/dnsproxy-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs:
      - build
    if: ${{ always() && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
        uses: technote-space/workflow-conclusion-action@v1
      - name: Send Slack notif
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: workflow, repo, message, commit, author, eventName, ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
